name: GitHub Actions Demo
on: [push]

jobs:
  Example-Action-Job:
    name: Exploring GitHub Actions
    runs-on: ubuntu-latest

    steps: 
      # Display the event that triggered the workflow
      - run: echo "The job was triggered by a ${{ github.event_name }} event."

      # Runner information
      - run: echo "The job is running on a ${{ runner.os }} server hosted by GitHub."

      # Information about repository and branch
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}." 

      # Use Action located in https://github.com/actions
      - name: Checkout repository code
        uses: actions/checkout@v4

      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Your repository has been copied to the path ${{ github.workspace }}  on the runner."
      - run: echo "Your workflow is now ready to test your code on the runner."

      - name: Conditional step when event name is pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "This event is a pull request"

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
           
      - name: Step dotnet on runner
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'

      - name: Display DotNet version
        run: dotnet --version

      - run: echo "The preinstalled tools are located here on the runner ${{ runner.tool_cache }}"

      - name: List files in the tool cache
        run: |
          ls ${{ runner.tools_cache }}

      - run: echo "This job's status is ${{ job.status }}. "


  Second-Job:
    name: Second Job running on an other runner
    runs-on: ubuntu-latest
    needs: Example-Action-Job
    
    steps:
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
        


  
  
